version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - START_BLOCK=${START_BLOCK:-0}
      - CHUNK_SIZE=${CHUNK_SIZE:-500}
      - CHAIN_ID=${CHAIN_ID:-137}
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
