version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - ENABLED_CHAINS=${ENABLED_CHAINS}
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - BASE_RPC_URL=${BASE_RPC_URL}
      - BSC_RPC_URL=${BSC_RPC_URL}
      - OPTIMISM_RPC_URL=${OPTIMISM_RPC_URL}
      - GNOSIS_RPC_URL=${GNOSIS_RPC_URL}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CHUNK_SIZE=${CHUNK_SIZE:-500}
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
